#!/bin/bash
### Script de hablar con passwd ###

### Variables ###
FILE1="grub.old"
FILE2="passwd"

### Dialogo ###
clear
echo -e "$ ${BLUE}$PLAYER${NC}: ¿Por qué ese archivo se ve tan enigmático? Actúa como sospechoso, como si tuviera un secreto que no le cuenta a nadie." | pv -qL100
echo -e "$ ${GREEN}$FILE1${NC}: No es para menos, él no es nada más, ni nada menos, quién permite cambiar la contraseña de los usuarios." | pv -qL100
echo -e "$ ${BLUE}$PLAYER${NC}: No quiero ni pensar lo que pasaría si no estuviera de nuestro lado." | pv -qL100
echo -e "$ ${YELLOW}$FILE2${NC}: /$!%43543!415$”#!" | pv -qL100
echo -e "$ ${BLUE}$PLAYER${NC}: ¿Que? ¿tiene algún problema? ¿está corrompido?" | pv -qL100
echo -e "$ ${GREEN}$FILE1${NC}: No, todo para él es una contraseña, mejor sigamos." | pv -qL100

### Fin del dialogo ###
press_enter
